create table resume_task (
    task_id varchar(80) primary key,
    resume_id varchar(80) not null,
    base_version bigint not null,
    status varchar(32) not null,
    workflow_summary varchar(512),
    failure_code varchar(80),
    failure_retryable boolean not null,
    attempt integer not null,
    repair_count integer not null,
    trace_id varchar(80) not null,
    lease_owner varchar(120),
    lease_until timestamp with time zone,
    domain_revision bigint not null,
    lock_version bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_resume_task_status_lease on resume_task(status, lease_until);

create table resume_version (
    resume_id varchar(80) not null,
    version_no bigint not null,
    schema_version integer not null,
    document_json text not null,
    actor varchar(80) not null,
    source_task_id varchar(80),
    created_at timestamp with time zone not null,
    primary key (resume_id, version_no)
);

create table resume_patch (
    patch_id varchar(80) not null,
    task_id varchar(80) not null,
    resume_id varchar(80) not null,
    base_version bigint not null,
    patch_json text not null,
    policy_decision varchar(24) not null,
    review_status varchar(24) not null,
    lock_version bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    primary key (task_id, patch_id)
);

create index idx_resume_patch_task on resume_patch(task_id);

create table evidence_artifact (
    artifact_id varchar(100) primary key,
    task_id varchar(80) not null,
    resume_id varchar(80) not null,
    source_type varchar(40) not null,
    source_ref varchar(512) not null,
    excerpt_text text not null,
    content_hash varchar(96) not null,
    approval_status varchar(24) not null,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null
);

create index idx_evidence_artifact_task on evidence_artifact(task_id);

create table task_event (
    event_id bigint generated by default as identity primary key,
    task_id varchar(80) not null,
    event_type varchar(100) not null,
    stage varchar(32) not null,
    attempt integer not null,
    trace_id varchar(80) not null,
    data_json text not null,
    occurred_at timestamp with time zone not null
);

create index idx_task_event_task_cursor on task_event(task_id, event_id);

create table workflow_checkpoint (
    checkpoint_id bigint generated by default as identity primary key,
    task_id varchar(80) not null,
    node_name varchar(48) not null,
    attempt integer not null,
    checkpoint_status varchar(24) not null,
    input_hash varchar(96),
    output_hash varchar(96),
    error_code varchar(80),
    updated_at timestamp with time zone not null
);

create index idx_workflow_checkpoint_latest on workflow_checkpoint(task_id, node_name, checkpoint_id);

create table idempotency_record (
    scope_name varchar(160) not null,
    idempotency_key varchar(160) not null,
    request_hash varchar(96) not null,
    response_status integer not null,
    response_body text not null,
    created_at timestamp with time zone not null,
    primary key (scope_name, idempotency_key)
);
