spring:
  application:
    name: tsumi-resume-orchestrator
  profiles:
    default: local
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
